import {requiredExecutionResources,publicEntries} from '../../dist/src/resources/inventory.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,readFileSync,mkdirSync,unlinkSync} from 'node:fs';import {join,dirname} from 'node:path';import {tmpdir} from 'node:os';
import {validatePlan} from '../../dist/src/validation/plan.js';import {sha256} from '../../dist/src/resources/resolve.js';
import {validateSchema} from '../../dist/src/validation/schema.js';
import {plan,assignment} from '../fixtures/execution.mjs';
function fixture(){const root=mkdtempSync(join(tmpdir(),'verification-execution-contract-'));const identity={repository:'https://github.com/test-fixture/verification-platform',tag:'v0.0.1',sourceCommit:'f'.repeat(40)};const values={integration:'test fixture',schema:readFileSync('schemas/browser-verification-plan.schema.json','utf8'),descriptors:'{"schemaVersion":1,"providers":[]}',runtime:'fixture',frontend:'fixture'};const resources=Object.entries(values).map(([id,bytes])=>({id,path:id,sha256:sha256(bytes),formatVersion:1,kind:id==='runtime'?'runtime':id==='frontend'?'frontend':'normative',dependencies:[]}));for(const r of resources)writeFileSync(join(root,r.path),values[r.id]);for(const expected of requiredExecutionResources){const path=join(root,expected.path);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,'synthetic indexed fixture');resources.push({...expected,sha256:sha256('synthetic indexed fixture'),formatVersion:1,dependencies:[],...(publicEntries[expected.id]?{entry:publicEntries[expected.id]}:{})});}const index=JSON.stringify({schemaVersion:1,...identity,resources});writeFileSync(join(root,'index'),index);const binding={schemaVersion:1,...identity,index:{asset:'index',sha256:sha256(index)},resources:{integration:'integration',planSchema:'schema',descriptors:'descriptors'}};const current=structuredClone(plan);current.configurationReferences[0].disposition='realized';writeFileSync(join(root,current.configurationReferences[0].path),'fixture');const a=structuredClone(assignment);const bytes=JSON.stringify(current);a.planDigest=sha256(bytes);a.authorization.planDigest=a.planDigest;a.bindingDigest=sha256(JSON.stringify(binding));a.authorization.bindingDigest=a.bindingDigest;return {planBytes:bytes,binding,resolution:{root,indexPath:'index',mode:'execution'},assignment:a,projectRoot:root};}
test('execution realized config and narrowed authorization validates; malformed assignment stays diagnostic',()=>{const f=fixture();assert.equal(validatePlan(f).valid,true);f.assignment={schemaVersion:1};assert.equal(validatePlan(f).valid,false);});
test('authorization can cover union of claim effects or narrow it without weakening obligations',()=>{const f=fixture();const p=JSON.parse(f.planBytes);p.claims[0].allowedEffects=['one'];p.claims.push({...structuredClone(p.claims[0]),id:'second',proof:[{...p.claims[0].proof[0],id:'second-proof'}],allowedEffects:['two']});f.planBytes=JSON.stringify(p);f.assignment.planDigest=sha256(f.planBytes);f.assignment.authorization.planDigest=f.assignment.planDigest;f.assignment.authorization.allowedEffects=['one','two'];assert.equal(validatePlan(f).valid,true);f.assignment.authorization.allowedEffects=['one'];assert.equal(validatePlan(f).valid,true);f.assignment.authorization.allowedEffects=['three'];assert.equal(validatePlan(f).valid,false);});
test('transient invocation and generation-blocked return serialize through public contracts',()=>{const f=fixture();assert.deepEqual(validateSchema('invocation',{schemaVersion:1,planPath:'browser-verification-plan.json',planDigest:f.assignment.planDigest,binding:f.binding,assignment:f.assignment}),[]);assert.deepEqual(validateSchema('invocation-return',{schemaVersion:1,status:'generation-blocked',evidence:[],runnerExitCode:null,acceptanceExitCode:1,diagnostics:['Assigned capability unestablished']}),[]);});
test('approved planned reference requires delivered file without rewriting normative plan progress',()=>{const f=fixture(),p=JSON.parse(f.planBytes);p.configurationReferences[0].disposition='planned';f.planBytes=JSON.stringify(p);f.assignment.planDigest=sha256(f.planBytes);f.assignment.authorization.planDigest=f.assignment.planDigest;const original=f.planBytes;unlinkSync(join(f.projectRoot,p.configurationReferences[0].path));assert.equal(validatePlan(f).valid,false);writeFileSync(join(f.projectRoot,p.configurationReferences[0].path),'delivered configuration');assert.equal(validatePlan(f).valid,true);assert.equal(f.planBytes,original);});
