import {rmSync} from 'node:fs';
// dist is exclusively generated by this build. Never package obsolete assets
// from earlier builds after a canonical source move/deletion.
rmSync(new URL('../dist/',import.meta.url),{recursive:true,force:true});
