import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';
import * as runtime from '../../dist/runtime/index.js';import {validateSchema} from '../../dist/src/validation/schema.js';
import {discoverProviders} from '../../dist/src/compilation/bundle.js';
test('actual exported generic catalog is the exact indexed normative JSON with honest implemented entries',()=>{const indexed=JSON.parse(readFileSync('contracts/generic-descriptors.json','utf8'));assert.deepEqual(runtime.descriptors,indexed.providers);assert.deepEqual(validateSchema('descriptor-set',indexed),[]);for(const provider of runtime.descriptors)for(const cap of provider.capabilities){assert.equal(typeof runtime[cap.export],'function',cap.id);assert(['unestablished','established','unavailable'].includes(cap.support));if(cap.support==='established')assert(cap.evidenceRefs.length>0);for(const ref of cap.evidenceRefs)assert(existsSync(ref.split('#')[0]),'Evidence documentation exists: '+ref);}assert(runtime.descriptors.flatMap(p=>p.capabilities).some(c=>c.export==='nativeOperation'));assert(runtime.unavailableCapabilities.some(c=>c.capabilityId==='chrome:worker-interruption'));});
test('real shared runtime descriptor collection discovers exactly configured generic provider',async()=>{const p=runtime.descriptors.find(p=>p.id==='generic:chrome');const discovered=await discoverProviders({assignment:{providers:[{id:p.id,version:p.version,entry:p.entry}]}},process.cwd());assert.deepEqual(discovered.diagnostics,[]);assert.equal(discovered.providers.length,1);assert.deepEqual(discovered.providers[0],p);});

test('empirical support stays within established observation families and unavailable control remains blocked',()=>{const caps=runtime.descriptors.flatMap(p=>p.capabilities);assert.deepEqual(caps.filter(c=>c.support==='established').map(c=>c.id).sort(),['chrome:network-observer','chrome:permission-observation','chrome:target-observer','native:menu']);const chrome=runtime.descriptors.find(p=>p.id==='generic:chrome');const ready=runtime.capabilityReadiness(chrome,'assigned',{available:true,reason:'fresh assigned source',evidenceRefs:['current-runtime']});assert.equal(ready.find(r=>r.capabilityId==='chrome:worker-interruption').status,'unavailable');});

test('unavailable catalog never contradicts established capability support',()=>{const established=new Set(runtime.descriptors.flatMap(p=>p.capabilities).filter(c=>c.support==='established').map(c=>c.id));for(const disposition of runtime.unavailableCapabilities){assert.notEqual(disposition.support,'established');assert.equal(established.has(disposition.capabilityId),false,disposition.capabilityId);}});

test('established native menu generation still requires fresh evidence',()=>{const provider=runtime.descriptors.find(p=>p.id==='generic:native');const cap=provider.capabilities.find(c=>c.id==='native:menu');assert(cap);assert.equal(cap.export,'nativeMenuPath');assert.equal(cap.support,'established');const prerequisites={available:true,reason:'synthetic source',evidenceRefs:['synthetic-runtime']};const unestablished=structuredClone(provider);unestablished.capabilities.find(c=>c.id===cap.id).support='unestablished';assert.equal(runtime.capabilityReadiness(unestablished,'fixture',prerequisites).find(r=>r.capabilityId===cap.id).status,'unavailable');assert.equal(runtime.capabilityReadiness(provider,'fixture',prerequisites).find(r=>r.capabilityId===cap.id).status,'available');assert.equal(runtime.capabilityReadiness(provider,'fixture',{...prerequisites,evidenceRefs:[]}).find(r=>r.capabilityId===cap.id).status,'unavailable');});
