import test from 'node:test';import assert from 'node:assert/strict';import childProcess from 'node:child_process';import {syncBuiltinESMExports} from 'node:module';import {EventEmitter} from 'node:events';import {PassThrough} from 'node:stream';
import {nativeMenuPath} from '../../dist/runtime/host/wsl-windows/native-menu.js';
const runtime={process_id:1,started_at:'incarnation',webSocketDebuggerUrl:'ws://fixture/devtools/browser/owned'};
const node=(name,id)=>({name,runtimeId:[id],patterns:['InvokePattern','ExpandCollapsePattern']});
function fixture(t,options={}){
 const calls=[],events=[];let title='Original',closed=false;
 const page={isClosed:()=>closed,title:async()=>title,bringToFront:async()=>events.push('foreground'),evaluate:async(_fn,arg)=>{if(arg===undefined)return 'document-token';if(typeof arg==='string'){if(String(_fn).includes('document.title=nonce'))title=arg;return 'document-token';}if(arg.token==='document-token'&&title===arg.nonce)title=arg.title;},context:()=>({newCDPSession:async()=>({send:async(method,params)=>{if(method==='Runtime.evaluate')return {result:{objectId:'exact-dom-object'}};if(method==='DOM.describeNode')return {node:{backendNodeId:123}};if(method==='Runtime.releaseObject')return {};if(method==='Input.dispatchMouseEvent'){events.push('cdp:'+params.type);if(params.type==='mousePressed'){events.push('input');if(options.inputError)throw Error('input transport lost');}return {};}return {targetInfo:{targetId:'target-owned'}};},detach:async()=>events.push('detach')})})};
 const handle={evaluate:async(_fn,arg)=>arg?.x!==undefined?!options.badHit:!options.staleDom,boundingBox:async()=>options.noGeometry?null:({x:20,y:30,width:80,height:40}),dispose:async()=>{}};
 const source={elementHandle:async()=>handle,page:()=>page,click:async()=>{events.push('input');if(options.inputError)throw Error('input transport lost');},focus:async()=>{},press:async()=>events.push('input')};
 let validates=0;
 const hostSession={provenance:runtime,endpoint:'borrowed',dispose:async()=>{},revalidate:async()=>{validates++;events.push('validate');if(options.lossAt===validates){closed=true;throw Error('Owned relay lost');}}};
 const mocked=t.mock.method(childProcess,'spawn',(command,args)=>{const child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.stdin=new PassThrough();child.exitCode=null;child.kill=()=>true;queueMicrotask(()=>{
 if(command==='wslpath'){child.stdout.write('fixture-path\n');child.exitCode=0;child.emit('close',0);return;}
 const operation=args[args.indexOf('-Operation')+1],menu=JSON.parse(args[args.indexOf('-MenuRequest')+1]);calls.push({operation,menu});events.push(operation);
 let value;if(operation==='menu-bind')value={window:node('window',1),runtime,menuRoots:[]};
 else if(operation==='menu-focus')value={revalidation:{status:'ok',runtime,window:node('window',1)},focus:{status:'ok',foregroundVerified:true,runtime}};
 else if(operation==='menu-tree')value=menu.rootRuntimeId?{root:node('Root',menu.rootRuntimeId[0]),item:node(menu.path[0],menu.rootRuntimeId[0]+10)}:[node('Root',2)];
 else if(operation==='menu-next')value=[node('Submenu',3)];else value={revalidation:{status:'ok',runtime},item:node(menu.path[0],menu.elementRuntimeId[0])};
 const override=options.respond?.(operation,menu);if(override!==undefined)value=override;
 if(value?.error){child.stdout.write(JSON.stringify({status:'error',detail:value.error,phase:value.attempted?'action':'observation',attempted:!!value.attempted}));child.exitCode=1;child.emit('close',1);}
 else{child.stdout.write(JSON.stringify({status:'ok',operation,data:value,observedAt:new Date().toISOString(),attempted:operation==='menu-focus'||operation==='menu-invoke'||operation==='menu-expand'}));child.exitCode=0;child.emit('close',0);}
 });return child;});syncBuiltinESMExports();
 return {calls,events,page,input:{page,source,path:['Parent','Command'],hostSession,host:{powershell:'fixture',runtimeConfig:'fixture'},deadlineMs:3000,initiation:options.keyboard?'keyboard':'right-click'},title:()=>title,restore:()=>{mocked.mock.restore();syncBuiltinESMExports();}};
}
test('exact menu path retains each native identity, session continuity, ordered correlation and serializable evidence',async t=>{const f=fixture(t);try{let count=0;f.input.correlation={source:'caller page state',observe:async page=>{assert.equal(page,f.page);f.events.push('correlation');return ++count;},matches:(before,after)=>before===1&&after===2};const result=await nativeMenuPath(f.input);assert.equal(result.verdict,'PASS');assert.equal(result.status,'invoked');assert.equal(result.targetId,'target-owned');assert.deepEqual(result.runtime,runtime);assert.match(result.lifecycleId,/^[a-f0-9-]+$/);assert.equal(f.title(),'Original');assert.deepEqual(f.calls.filter(c=>c.operation==='menu-expand'||c.operation==='menu-invoke').map(c=>({operation:c.operation,path:c.menu.path,root:c.menu.rootRuntimeId,item:c.menu.elementRuntimeId,ancestors:c.menu.ancestors})),[{operation:'menu-expand',path:['Parent'],root:[2],item:[12],ancestors:[]},{operation:'menu-invoke',path:['Command'],root:[3],item:[13],ancestors:[{label:'Parent',rootRuntimeId:[2],elementRuntimeId:[12]}]}]);assert(f.events.indexOf('correlation')<f.events.indexOf('input'));assert(f.events.lastIndexOf('correlation')>f.events.indexOf('menu-invoke'));assert.equal(JSON.parse(JSON.stringify(result)).observations.length,result.observations.length);}finally{f.restore();}});
for(const [name,respond] of [
 ['missing menu',op=>op==='menu-tree'?[]:undefined],
 ['duplicate roots',op=>op==='menu-tree'?[node('Root',2),node('Other',3)]:undefined],
 ['missing first-level label',(op,m)=>op==='menu-tree'&&m.path?{error:'UIA element not found.'}:undefined],
 ['missing submenu',(op)=>op==='menu-next'?[]:undefined],
 ['duplicate submenu',(op)=>op==='menu-next'?[node('Submenu',3),node('Submenu',4)]:undefined],
 ['missing second-level label',(op,m)=>op==='menu-tree'&&m.path?.[0]==='Command'?{error:'UIA element not found.'}:undefined],
 ['stale retained item',(op)=>op==='menu-invoke'?{error:'Menu item changed before action.'}:undefined],
 ['unsupported semantic pattern',(op)=>op==='menu-expand'?{error:'Unsupported ExpandCollapsePattern; no action performed.'}:undefined]
])test(name+' fails closed without repeating an action',async t=>{const f=fixture(t,{respond});try{const result=await nativeMenuPath(f.input);assert.equal(result.verdict,'BLOCKED');assert.equal(f.calls.filter(c=>c.operation==='menu-invoke').length,name==='stale retained item'?1:0);assert.equal(f.title(),'Original');}finally{f.restore();}});
test('source loss rejects action and uncertain page input retains attempted evidence and cleanup',async t=>{for(const options of [{lossAt:2},{inputError:true}]){const f=fixture(t,options);try{const result=await nativeMenuPath(f.input);assert.equal(result.verdict,options.inputError?'INCONCLUSIVE':'BLOCKED');assert.equal(result.attempted,!!options.inputError);assert(!f.calls.some(c=>c.operation==='menu-invoke'));if(options.inputError)assert.equal(f.title(),'Original');}finally{f.restore();}}});
test('correlated effect mismatch reports FAIL after native invocation',async t=>{const f=fixture(t);try{f.input.path=['Command'];f.input.correlation={source:'existing page semantic state',observe:async()=>({value:1}),matches:()=>false};const result=await nativeMenuPath(f.input);assert.equal(result.status,'invoked');assert.equal(result.verdict,'FAIL');assert.equal(result.correlation.matched,false);}finally{f.restore();}});
test('invalid initiation blocks before browser mutation or input',async t=>{const f=fixture(t);try{f.input.initiation='fallback';const result=await nativeMenuPath(f.input);assert.equal(result.verdict,'BLOCKED');assert.equal(result.attempted,false);assert.equal(f.title(),'Original');assert.deepEqual(f.events,[]);}finally{f.restore();}});

test('single-level exact native path invokes once without expansion and restores borrowed document',async t=>{const f=fixture(t);try{f.input.path=['Command'];const result=await nativeMenuPath(f.input);assert.equal(result.verdict,'PASS');assert.equal(result.status,'invoked');assert.equal(result.attempted,true);assert.deepEqual(f.calls.filter(c=>c.operation==='menu-invoke').map(c=>({path:c.menu.path,root:c.menu.rootRuntimeId,item:c.menu.elementRuntimeId,ancestors:c.menu.ancestors})),[{path:['Command'],root:[2],item:[12],ancestors:[]}]);assert(!f.calls.some(c=>c.operation==='menu-expand'||c.operation==='menu-next'));assert.equal(f.title(),'Original');assert(f.events.includes('detach'));}finally{f.restore();}});
for(const detail of ['Bound native window changed.','Menu runtime incarnation changed.'])test(detail+' rejects native invocation after source revalidation loss',async t=>{const f=fixture(t,{respond:op=>op==='menu-invoke'?{error:detail}:undefined});try{const result=await nativeMenuPath(f.input);assert.equal(result.verdict,'BLOCKED');assert.equal(result.detail,detail);const failed=result.observations.at(-1);assert.equal(failed.attempted,false);assert.equal(failed.uncertain,false);assert.equal(f.calls.filter(c=>c.operation==='menu-invoke').length,1);assert.equal(f.title(),'Original');}finally{f.restore();}});

test('verified native foreground acquisition completes before correlation baseline and source menu input',async t=>{const f=fixture(t,{keyboard:true});try{const result=await nativeMenuPath(f.input);assert.equal(result.verdict,'PASS');assert(f.events.indexOf('menu-bind')<f.events.indexOf('menu-focus'));assert(f.events.indexOf('menu-focus')<f.events.indexOf('input'));assert.equal(f.calls.filter(c=>c.operation==='menu-focus').length,1);const focus=f.calls.find(c=>c.operation==='menu-focus');assert.deepEqual(focus.menu.windowRuntimeId,[1]);assert.deepEqual(focus.menu.runtime,runtime);const observed=result.observations.find(o=>o.observation?.operation==='menu-focus');assert.equal(observed.observation.data.focus.foregroundVerified,true);}finally{f.restore();}});
for(const [name,attempted,verdict] of [['unsupported native focus',false,'BLOCKED'],['foreground verification absent after possible focus',true,'INCONCLUSIVE']])test(name+' prevents menu initiation without focus retry',async t=>{const f=fixture(t,{keyboard:true,respond:op=>op==='menu-focus'?{error:name,attempted}:undefined});try{const result=await nativeMenuPath(f.input);assert.equal(result.verdict,verdict);assert.equal(result.attempted,attempted);assert(!f.events.includes('input'));assert.equal(f.calls.filter(c=>c.operation==='menu-focus').length,1);assert.equal(f.title(),'Original');}finally{f.restore();}});

test('post-focus binding requires foreground and source foreground loss rejects input',async t=>{const f=fixture(t,{keyboard:true,respond:(op,menu)=>op==='menu-bind'&&menu.requireForeground?{error:'Exact source window is not foreground.'}:undefined});try{const result=await nativeMenuPath(f.input);assert.equal(result.verdict,'BLOCKED');assert.equal(result.attempted,true);assert(!f.events.includes('input'));assert.equal(f.calls.filter(c=>c.operation==='menu-focus').length,1);const bindings=f.calls.filter(c=>c.operation==='menu-bind');assert.equal(bindings.length,2);assert.equal(bindings[0].menu.requireForeground,undefined);assert.equal(bindings[1].menu.requireForeground,true);assert.equal(f.title(),'Original');}finally{f.restore();}});

test('right-click retains exact DOM identity and fresh CSS geometry then dispatches only through target CDP',async t=>{const f=fixture(t);try{const result=await nativeMenuPath(f.input);assert.equal(result.verdict,'PASS');assert(!f.events.includes('foreground'));assert(!f.calls.some(c=>c.operation==='menu-focus'));assert(f.calls.every(c=>c.menu.foregroundFree===true));assert.deepEqual(result.initiationEvidence.coordinates,{x:60,y:50});assert.equal(result.initiationEvidence.identityConfirmed,true);assert.deepEqual(result.initiationEvidence.domIdentity,{backendNodeId:123,documentToken:'document-token'});assert(result.initiationEvidence.events.every(e=>e.sentAt&&e.acknowledgedAt));assert.deepEqual(f.events.filter(e=>e.startsWith('cdp:')),['cdp:mousePressed','cdp:mouseReleased']);}finally{f.restore();}});
for(const options of [{staleDom:true},{noGeometry:true},{badHit:true}])test('invalid exact DOM identity or geometry blocks CDP input '+JSON.stringify(options),async t=>{const f=fixture(t,options);try{const result=await nativeMenuPath(f.input);assert.equal(result.verdict,'BLOCKED');assert.equal(result.attempted,false);assert(!f.events.includes('input'));}finally{f.restore();}});
test('submenu association evidence crosses helper calls and retained ancestor frames',async t=>{const association={parentRuntimeId:[12],parentLabel:'Parent',rootRuntimeId:[2],boundWindowHandle:9,before:[],beforeAt:'2026-10-09T00:00:00Z',expandedAt:'2026-10-09T00:00:01Z',expandDecision:'expanded'};const selected={...association,selectedRuntimeId:[3],selectedHandle:10,decision:'unique-sibling'};const f=fixture(t,{respond:op=>op==='menu-expand'?{association}:op==='menu-next'?[{...node('Parent',3),association:selected}]:undefined});try{const result=await nativeMenuPath(f.input);assert.equal(result.verdict,'PASS');assert.deepEqual(f.calls.find(c=>c.operation==='menu-next').menu.association,association);assert.deepEqual(f.calls.find(c=>c.operation==='menu-invoke').menu.ancestors[0].association,selected);}finally{f.restore();}});
