import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';
import {observeTargets} from '../../dist/runtime/cdp/target-observer.js';
import {observeNetwork} from '../../dist/runtime/cdp/network-observer.js';
test('target discovery reconciles subscription events and bounded overflow with owned detach',async()=>{const cdp=new EventEmitter();let detached=0;cdp.detach=async()=>detached++;cdp.send=async(method)=>{if(method==='Target.setDiscoverTargets'){cdp.emit('Target.targetCreated',{targetInfo:{targetId:'fresh',type:'worker'}});return {};}if(method==='Target.getTargets')return {targetInfos:[{targetId:'fresh',type:'worker'}]};};const browser=new EventEmitter();browser.newBrowserCDPSession=async()=>cdp;const observer=await observeTargets(browser,[{type:'worker',exclude:false},{exclude:true}],1);assert(observer.ready);assert.equal(observer.observations.length,1);cdp.emit('Target.targetDestroyed',{targetId:'fresh'});assert(observer.loss.includes('overflow'));await observer.dispose();await observer.dispose();assert.equal(detached,1);});
test('network preserves actual raw fields/source identity finite window and loss without attribution guesses',async()=>{const cdp=new EventEmitter();cdp.send=async()=>({});const controller=new AbortController();const observer=await observeNetwork(cdp,{sourceId:'worker-source',sessionId:'session',targetId:'worker',type:'worker',identityNamespace:'cdp.target',limit:2,lossSignal:controller.signal});const raw={requestId:'same',loaderId:'',initiator:{type:'other'},frameId:'cdp-frame'};cdp.emit('Network.requestWillBeSent',raw);controller.abort();const result=observer.finish();assert.equal(result.complete,false);assert.deepEqual(result.observations[0].raw,raw);assert.equal(result.observations[0].sourceId,'worker-source');assert.equal(cdp.listenerCount('Network.requestWillBeSent'),0);});
test('discovery buffer overflow and session loss invalidate finite target proof',async()=>{const cdp=new EventEmitter();cdp.detach=async()=>{};cdp.send=async(method)=>{if(method==='Target.setDiscoverTargets'){for(let i=0;i<3;i++)cdp.emit('Target.targetCreated',{targetInfo:{targetId:String(i),type:'worker'}});return {};}return {targetInfos:[]};};const browser=new EventEmitter();browser.newBrowserCDPSession=async()=>cdp;const observer=await observeTargets(browser,[{exclude:false}],1);assert.equal(observer.observations.length,1);cdp.emit('close',cdp);const result=await observer.finish();assert.equal(result.complete,false);assert(result.loss.includes('overflow'));assert(result.loss.includes('target-session-lost'));});
test('source lost during network readiness cannot return healthy observer',async()=>{const cdp=new EventEmitter();const controller=new AbortController();cdp.send=async()=>{controller.abort();return {};};await assert.rejects(()=>observeNetwork(cdp,{sourceId:'page',sessionId:'session',targetId:'target',type:'page',identityNamespace:'cdp.target',limit:1,lossSignal:controller.signal}),/lost during subscription/);assert.equal(cdp.listenerCount('Network.requestWillBeSent'),0);});

test('network close invalidates scoped coverage and records readiness interval',async()=>{const cdp=new EventEmitter();cdp.send=async()=>({});const controller=new AbortController();const observer=await observeNetwork(cdp,{sourceId:'page',sessionId:'session',targetId:'target',type:'page',identityNamespace:'cdp.target',limit:1,lossSignal:controller.signal});cdp.emit('close');const result=observer.finish();assert.equal(result.complete,false);assert(result.readyAt>=result.start);assert(result.end>=result.readyAt);assert.deepEqual(result.scope,{sourceId:'page',sessionId:'session',sessionIdentityNamespace:'provider.session',targetId:'target',type:'page',identityNamespace:'cdp.target'});assert.equal(cdp.listenerCount('close'),0);});

test('CDP close during network enable cannot signal ready even without AbortSignal loss',async()=>{const cdp=new EventEmitter();cdp.send=async()=>{cdp.emit('close');return {};};const controller=new AbortController();await assert.rejects(()=>observeNetwork(cdp,{sourceId:'page',sessionId:'session',targetId:'target',type:'page',identityNamespace:'cdp.target',limit:1,lossSignal:controller.signal}),/lost during subscription readiness/);assert.equal(cdp.listenerCount('close'),0);});
test('target CDP close during discovery cannot signal live readiness',async()=>{const cdp=new EventEmitter();let detached=0;cdp.detach=async()=>detached++;cdp.send=async(method)=>{if(method==='Target.getTargets'){cdp.emit('close');return {targetInfos:[]};}return {};};const browser=new EventEmitter();browser.newBrowserCDPSession=async()=>cdp;await assert.rejects(()=>observeTargets(browser,[{type:'worker',exclude:false},{exclude:true}],2),/lost during discovery readiness/);assert.equal(detached,1);assert.equal(cdp.listenerCount('close'),0);});
