import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {reconcile} from '../../dist/runtime/evidence/reconcile.js';
import {validateSchema} from '../../dist/src/validation/schema.js';
import {plan,assignment,identity,manifest,evidence,record,provider} from '../fixtures/execution.mjs';
import {capabilityReadiness} from '../../dist/runtime/readiness.js';
function input(){const outputRoot=mkdtempSync(join(tmpdir(),'verification-result-'));writeFileSync(join(outputRoot,'raw.json'),'{}');return {plan,assignment,identity,manifest:structuredClone(manifest),evidence:[structuredClone(evidence)],records:[structuredClone(record)],outputRoot,runner:{exitCode:0,status:'passed'}};}
test('serialized contract milestones and actual ordinary runner fixture imports',async()=>{for(const [schema,value] of [['provider-descriptor',provider],['assignment',assignment],['coverage-manifest',manifest],['evidence',evidence],['claim-record',record]])assert.deepEqual(validateSchema(schema,value),[],schema);const fixture=await import('../../dist/runtime/fixtures.js');assert.equal(typeof fixture.test.extend,'function');assert.equal(typeof fixture.expect,'function');});
test('all four outcomes retain full coverage and runner status',()=>{const p=input();assert.equal(reconcile(p).verdict,'PASS');p.records[0].outcome='contradicted';p.runner={exitCode:1,status:'failed'};assert.equal(reconcile(p).verdict,'FAIL');p.records=[];p.manifest.entries[0].blocker='Assigned capability missing';assert.equal(reconcile(p).verdict,'BLOCKED');delete p.manifest.entries[0].blocker;assert.equal(reconcile(p).verdict,'INCONCLUSIVE');});
test('attempt uncertainty, missing attachment, identity and proof-relevant cleanup never pass',()=>{for(const change of [p=>p.evidence=[],p=>p.records[0].identity={...identity,generatedSourceDigest:'d'.repeat(64)},p=>p.evidence[0].provider.version='wrong',p=>p.records[0].proofRelevantCleanupFailed=true,p=>p.evidence[0].window.loss=['lost'],p=>p.evidence[0].attachment.path='missing']){const p=input();change(p);assert.equal(reconcile(p).verdict,'INCONCLUSIVE');}});
test('missing/extra pair and weakened mandatory evidence rejected before acceptance',()=>{const p=input();p.manifest.entries=[];assert.throws(()=>reconcile(p),/manifest|coverage/);const q=input();q.manifest.entries[0].proofIds=['invented'];assert.throws(()=>reconcile(q),/proof mapping/);});
test('decisive contradiction persists despite cleanup failure',()=>{const p=input();p.records[0].outcome='contradicted';p.records[0].proofRelevantCleanupFailed=true;assert.equal(reconcile(p).verdict,'FAIL');});
test('mandatory proof provenance and capability contract cannot be weakened',()=>{for(const mutate of [p=>p.evidence[0].source='fabricated-source',p=>p.evidence[0].provider.id='unapproved']){const p=input();mutate(p);assert.equal(reconcile(p).verdict,'INCONCLUSIVE');}for(const mutate of [p=>p.manifest.entries[0].capabilityIds=[],p=>p.manifest.entries[0].capabilityVersions['chrome:version']='2']){const p=input();mutate(p);assert.throws(()=>reconcile(p),/capability|Capability/);}});
test('readiness serialization never advertises mock-only unestablished support',()=>{const [ready]=capabilityReadiness(provider,'assigned-chrome',{available:true,reason:'fixture',evidenceRefs:['synthetic']});assert.deepEqual(validateSchema('readiness',ready),[]);assert.equal(ready.status,'unavailable');});
