import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {runInNewContext} from 'node:vm';
import {interruptWorker} from '../../dist/runtime/cdp/worker.js';import {observePermission} from '../../dist/runtime/cdp/permission.js';
function fixture(accept=true,destroy=true){const cdp=new EventEmitter();let targetId='old',wakeCount=0;const commands=[];cdp.detach=async()=>commands.push('detach');cdp.send=async(method,args)=>{commands.push([method,args]);if(method==='Target.getTargets')return {targetInfos:[{targetId,type:'worker',url:'blob:owned'}]};if(method==='Target.closeTarget'){if(destroy)cdp.emit('Target.targetDestroyed',{targetId});return {success:accept};}if(method==='Target.attachToTarget')return {sessionId:'new-session'};return {};};return {cdp,commands,browser:{newBrowserCDPSession:async()=>cdp},wake:async()=>{wakeCount++;targetId='new';},get wakeCount(){return wakeCount;}};}
test('exact assigned stop destruction precedes separately authorized wake and fresh session; owned cleanup once',async()=>{const f=fixture();const result=await interruptWorker(f.browser,{targetId:'old',url:'blob:owned',deadlineMs:100,wake:f.wake});assert.equal(result.replacement.targetId,'new');assert.equal(result.sessionId,'new-session');assert.equal(f.wakeCount,1);await result.dispose();await result.dispose();assert.equal(f.commands.filter(x=>x==='detach').length,1);assert.equal(f.cdp.listenerCount('Target.targetDestroyed'),0);});
test('unavailable stop never wakes or attaches replacement and detaches observer',async()=>{const f=fixture(false,false);await assert.rejects(()=>interruptWorker(f.browser,{targetId:'old',url:'blob:owned',deadlineMs:100,wake:f.wake}),/stop unavailable/);assert.equal(f.wakeCount,0);assert.equal(f.cdp.listenerCount('Target.targetDestroyed'),0);assert.equal(f.commands.at(-1),'detach');});
test('accepted stop without destruction is uncertain and never retried or woken',async()=>{const f=fixture(true,false);await assert.rejects(()=>interruptWorker(f.browser,{targetId:'old',url:'blob:owned',deadlineMs:10,wake:f.wake}),/destruction not observed/);assert.equal(f.wakeCount,0);assert.equal(f.commands.filter(x=>x[0]==='Target.closeTarget').length,1);});
test('stale exact assignment cannot stop another worker',async()=>{const f=fixture();await assert.rejects(()=>interruptWorker(f.browser,{targetId:'wrong',url:'blob:owned',deadlineMs:100,wake:f.wake}));assert.equal(f.commands.filter(x=>x[0]==='Target.closeTarget').length,0);});
test('permission read records actual source and origin without mutation',async()=>{const page={evaluate:async(fn,args)=>{assert.deepEqual(args,{origin:'https://owned.test',name:'notifications'});return {origin:args.origin,state:'prompt'};}};const result=await observePermission(page,'https://owned.test','notifications');assert.equal(result.source,'navigator.permissions');assert.equal(result.state,'prompt');assert(result.limits.some(x=>x.includes('extension-permission')));});

test('permission exact-origin guard prevents querying the wrong document',async()=>{let queries=0;const page={evaluate:async(fn,args)=>runInNewContext('('+fn.toString()+')(args)',{args,location:{origin:'https://other.test'},navigator:{permissions:{query:async()=>{queries++;return {state:'granted'};}}}})};await assert.rejects(()=>observePermission(page,'https://owned.test','notifications'),/origin mismatch/);assert.equal(queries,0);});
